version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  paint-db-server:
    image: paint-db-server:v0.1.0
    ports:
      - 4000:4000
    environment:
      PAINT_DB_MONGO_URI: mongodb://root:password@mongo/hobby?authSource=admin